##################################################
##
## THIS FILE IS GENERATED BY init.pl
##
##################################################

use DBI;

# Version
$g_version = "3.1";

# First boot
$g_chosenlanguage = 1;
$g_firstboot      = 0;

# System commands
$g_mv = (($^O eq "MSWin32") ? "move" : "mv");
$g_rm = (($^O eq "MSWin32") ? "del" : "rm");

# Language
$g_language = 'English';

# MySQL
$g_mysql_user = 'mbzdb';
$g_mysql_pass = 'mbzdb';
$g_mysql_name = 'mbzdb';
$g_mysql_host = 'localhost';
$g_mysql_port = '5432';

$g_tablespace = 'mbzdb';

$g_pending     = '"Pending"';
$g_pendingdata = '"PendingData"';

# Plugins
@g_active_plugins = ('livestats','pendinglog');

# Schema
# NOTE: we have to use schema11 because the latest revision of this file is for NGS which isn't implemented yet.
$g_schema_url = 'http://bugs.musicbrainz.org/browser/mb_server/branches/TemplateToolkit/admin/sql/CreateTables.sql?rev=11088&format=raw';
$g_index_url = 'http://bugs.musicbrainz.org/browser/mb_server/branches/TemplateToolkit/admin/sql/CreateIndexes.sql?rev=11088&format=raw';
$g_pk_url = 'http://bugs.musicbrainz.org/browser/mb_server/branches/TemplateToolkit/admin/sql/CreatePrimaryKeys.sql?rev=11088&format=raw';

# Ignore data
@g_ignore_tables = (
	'release_group_meta', 'release_group', 'release_groupusecount', 'release_groupwords', 'isrc',
	'trm', 'trmjoin'
);
@g_ignore_fields = ('release_group', 'release_groupusecount', 'trmids');

# Errors
$g_die_on_dupid  = 0;
$g_die_on_error  = 1;
$g_die_on_plugin = 0;

# Globals
$dbh = DBI->connect("dbi:Pg:dbname=$g_mysql_name;host=$g_mysql_host;port=$g_mysql_port", $g_mysql_user, $g_mysql_pass);

return 1;
